# Generated by Django 5.0.6 on 2025-09-19 02:57

import django.core.validators
import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='分类描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='store_categ_name_1278fd_idx'), models.Index(fields=['slug'], name='store_categ_slug_3348ec_idx'), models.Index(fields=['is_active', 'name'], name='store_categ_is_acti_a5969f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='产品标题', max_length=255)),
                ('author', models.CharField(default='admin', help_text='作者', max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='库存单位 (SKU)，自动生成', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='产品描述')),
                ('image', models.ImageField(help_text='产品图片 (最大5MB，支持jpg, png, gif, webp)', upload_to='products/%Y/%m/%d/', validators=[store.models.validate_image_size, store.models.validate_image_format])),
                ('slug', models.SlugField(help_text='URL友好标识', max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='价格 (最多99999999.99)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='折扣价格', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('in_stock', models.BooleanField(default=True, help_text='是否有库存')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
                ('featured', models.BooleanField(default=False, help_text='是否推荐')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='浏览次数')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='产品分类', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.category')),
                ('created_by', models.ForeignKey(help_text='创建者', on_delete=django.db.models.deletion.CASCADE, related_name='product_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='store_produ_name_181788_idx'), models.Index(fields=['slug'], name='store_produ_slug_29d658_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created'], name='store_produ_created_cee8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='store_produ_categor_591340_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='store_produ_slug_361302_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'in_stock'], name='store_produ_is_acti_59f91c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured', '-created'], name='store_produ_feature_512b65_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='store_produ_price_2d55a6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['view_count'], name='store_produ_view_co_3b9dca_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'is_approved'], name='store_produ_product_4ca518_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating'], name='store_produ_rating_b300a4_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['created_at'], name='store_produ_created_8072ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user')},
        ),
    ]
