# Generated by Django 5.2.3 on 2025-06-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS store_product_is_active_in_stock ON store_product(is_active, in_stock)",
            reverse_sql="DROP INDEX IF EXISTS store_product_is_active_in_stock"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS store_product_price ON store_product(price)",
            reverse_sql="DROP INDEX IF EXISTS store_product_price"
        ),
    ]
